# .streamlit/secrets.toml

[ftp]
host = "82.112.232.31"
user = "u363812745.vvd.in"
password = "5:qQCD]lwfaTsx?S"
primary_path = "/public_html/VVD_Hic/data_storage/primary.csv"
category_path = "/public_html/VVD_Hic/data_storage/prod_ctg.csv"